### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/server/players/PlayerList

### ISSUE THREAD

**Issue by retrovato123** [P3pp3rF1y/SophisticatedCore#293]
**Minecraft Version :** Minecraft 1.20.1 (Mohist o Arclight)

**Operating System :** Linux

**Concerned mod / plugin** : 
CarryOn: https://www.curseforge.com/minecraft/mc-mods/carry-on
Attributizer: https://www.curseforge.com/minecraft/mc-mods/attributizer
ModernFix: https://www.curseforge.com/minecraft/mc-mods/modernfix
Sophisticated Backpacks: https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
SophisticatedCore: https://www.curseforge.com/minecraft/mc-mods/sophisticated-core

**Logs :** https://gist.github.com/retrovato123/eadd71edc0836352e05176f9dbfe0863
**Steps to Reproduce :**
 1. Start server

**Description of issue :** It only doesn't work with those mods. If I remove them, everything works fine. If I use Forge, they also work, but when I updated Mohist o Arclight to 1.20.1, they stopped working. Previous versions do work.

**Comment by P3pp3rF1y** [comment]
Forge crashes because it can't find a class, I am guessing mohist is messing with that code or it's incorrect version of it for the forge version. Anyway this has nothing to do with sophisticatedcore other than SC calling a forge method that then fails later on because that class can't be found. So you will need to figure out what is the correct version of mohist for correct version of forge.
